Fix no_std support
atlas-aero/rt-PCA9539 pull request #3
Opened 2023-12-11 17:16 UTC by ayushagrawal2

Should fix #2 -- I haven't run into any issues yet in my usage over the past month.

2023-12-12 10:55 UTC, marius-meissner requested changes
Thank you! Looks good, just one minor suggestion.
Seems QA action pipeline is currently not triggered by PR.
Could you please adjust
https://github.com/atlas-aero/rt-PCA9539/blob/366bc6e345391a06eb4e5ae27709879cfa976bd2/.github/workflows/qa.yaml#L3 to 
```yaml
on:
  push:
  pull_request:
```

2023-12-12 10:55 UTC, marius-meissner commented on src/expander.rs
> +                .write(self.address, &[COMMAND_CONF_0, self.configuration_0.as_value().clone()]),
As u8 implements the Copy trait, no cloning is required, as also suggested by Clippy.
Please try to dereference/copy instead:
```rust
*self.configuration_0.as_value()
```

This also applies to lines 342, 351, 354, 363 and 366.

2023-12-12 18:24 UTC, ayushagrawal2 commented
Thanks for the feedback! Let me know if any further changes are needed

2023-12-18 11:29 UTC, marius-meissner commented
LGTM

2023-12-18 11:29 UTC, merged